language: node_js
dist: xenial

node_js:
 - "node"
 - "10"
 - "8"
 - "6"

env:
 - CONFIG: 'build-release'
 - CONFIG: 'build-watch'
 - CONFIG: 'package-darwin'
 - CONFIG: 'package-linux'
 - CONFIG: 'package-win32'

before_install: npm --dev update

script: npm run $CONFIG
