language: node_js
dist: xenial

node_js:
 - "node"
 - "12"
 - "10"
 - "8"

env:
 - CONFIG: 'package-darwin'
 - CONFIG: 'package-linux'
 - CONFIG: 'package-win32'
 - CONFIG: 'build-release'
 - CONFIG: 'build-watch'

script: npm run $CONFIG
