language: node_js
dist: xenial

node_js:
 - "node"
 - "10"

env:
 - CONFIG: 'build-release'
 - CONFIG: 'build-watch'
 - CONFIG: 'package-darwin'
 - CONFIG: 'package-linux'
 - CONFIG: 'package-win32'
 
script: npm run $CONFIG
