language: node_js
dist: xenial

node_js:
 - "node"
 - "10"
 - "8"
# - "6"

env:
# - CONFIG: 'package-darwin'
# - CONFIG: 'package-linux'
# - CONFIG: 'package-win32'
 - CONFIG: 'build-release'
 - CONFIG: 'build-watch'

script: npm run $CONFIG
