name: aomanalyzer
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: npm install
    - name: build
      run: npm install
      npm run build-release
